### PR TITLE
add callback func to allow ImGui Font setting.

### PR DESCRIPTION
**Pull request by xarthurx**
This PR tries to resolve issues described in: https://github.com/nmwsharp/polyscope/issues/133, https://github.com/nmwsharp/polyscope/issues/135.

add a callback function to the render::engine and its derivatives to allow external ImGui font setting when using `polyscope` as a library.

One issue that still exists is the `globalFontAtlas` variable cannot be set from the external function, though it looks that variable does not affect anything. But an additional step was added to make sure that variable is set after the font setting.

### CODE REVIEW

**Comment by xarthurx** [comment]
Additionally, setting ImGui styles from this callback function will be overwritten by the follow-up mechanism inside `polyscope::init()`.

So I'm still setting the styles inside the original `user_callback` function.

I would suggest separating the Gui settings (font and styles) from the engine side and exposing them to the user so that it may help resolve the issue better.

**Comment by xarthurx** [comment]
Based on the current setup, it seems we need to callback function to both `initializeImGui()` and `setImGuiStyle()` if we want to make the style settings also done during the initialization stage.

Though we can do dirty tricks like:
```cpp
  if (viewerOneTimeInit) {
    setupImGuityle();
    viewerOneTimeInit = false;
  }
```
inside the callback function to avoid repeating the style-setting in every loop.

**Comment by xarthurx** [comment]
And it seems the default menu was not affected by the font setting...

image

**Comment by nmwsharp** [comment]
Hi! First off, I see that there several issues/PRs related to this one, which I'm just getting to look at now. At the high level, I think that you are the first person to build a complex, custom UI on top of Polyscope, so there are probably a lot of pain-points to resolve. Thank you for taking the time to create issues and PRs!!

**Comment by nmwsharp** [comment]
I think that the solution in this PR is a good one. Most users probably will not need to customize the ImGUI UI, so we should leave the default flow as-is. However, if someone wants to do "advanced" customization, they can pass this callback and do whatever they want with ImGui.

One minor detail: I think that we should require users to assign to `regularFont` and `monoFont` in this callback. (it's fine if they assign the same font to both) They aren't used by Polyscope currently, but I'm hoping to use them in the future.

**Comment by nmwsharp** [comment]
To clarify, does this PR actually resolve your use-case in the current form? Or are there still issues with settings that get overwritten?

>Additionally, setting ImGui styles from this callback function will be overwritten by the follow-up mechanism inside polyscope::init().
> 
> So I'm still setting the styles inside the original user_callback function.

**Comment by xarthurx** [comment]
> To clarify, does this PR actually resolve your use-case in the current form? Or are there still issues with settings that get overwritten?
> 
> > Additionally, setting ImGui styles from this callback function will be overwritten by the follow-up mechanism inside polyscope::init().
> > So I'm still setting the styles inside the original user_callback function.

The font issue is resolved, but the UI style is not. I saw that in your `init()` func, there is some settings related to `Context` and activating the function of set GUI styles. So for now, I have to do it in the `callback` rather than during the initialization process.

Do you think it is possible to separate the GUI init from the current OpenGL init process, and make it into a virtual function that can be overwritten by the user?

I came to `polyscope` from the viewer in `libigl` because of the simplicity of adding different geometry types.
What the `libigl` allows is to redefine the viewer class and set everything the user like.

For the current structure of `polyscope`, since you use `namespace` rather than `Class`, it is not that modularized. Based on my understanding, the `Engine` (`gl_Engine`) is the shallowest class I can modify, and clearly, it is too deep for just customizing the Gui.

Since you've added the `buidGui` func for customization, I think it makes sense to separate all the GUI init process into a single virtual function, and call it in the `polyscope::init()`, and users can also override it with their own additional settings...

**Comment by nmwsharp** [comment]
OK, I think I will have to set up some code for this on my end to understand what can and cannot be done via the GUI callback as implemented here.

Virtual functions are a little inconvenient in the Polyscope setup, because the renderer class is constructed on the Polyscope side, so as-is there is no way for the user to subclass it.

I think the callback is a good solution, we just need to figure out the right way to expose it so that everything you want to do is possible.

**Comment by xarthurx** [comment]
@nmwsharp Is there any reason that all the GUI build functions, like `buildPolyscopeGui()` are under the `<unnamed>` scope, i.e. `polyscope::<unnamed>::buildPolyscopeGui()`?

I tried to disable the `options::buildGui` and re-use one of your default GUI, say only the control one, not the structure one, but in such definition, I cannot reuse your modularized function to build the GUI.

Additionally, I think the ImGui style issue still exists, even when the `buildGui` option is set to `false`.
To be specific:
Any settings I set before the `polyscope::init()` will be overwritten. I have to set it in the `usercallback` function, which will re-set the setting in every drawing iteration -- this should not be expected.

**Comment by xarthurx** [comment]
In general, I would agree with your approach to providing the `buildGui` option to allow customized GUI. I would further recommend modularizing the initialization approaches so that users can use them as building blocks.

For instance:

1. ImGui setting
  - style
  - font
2. polyscope default UI:
  - control
  - structure
  - user
...

**Comment by nmwsharp** [comment]
OK, I looked in to this some more. Thanks for your patience!

> Why functions in unnamed scope?

These functions are meant to be internal details, needed in that `.cpp` file only. Using an anonymous namespace is a habit to avoid accidentally violating the "one definition" rule. Otherwise, if two separate source files were to have functions named e.g. `void populateCache()`, then this would lead to linker errors. However if both functions are in anonymous namespaces, there is nothing to worry about. For that reason I always put helper methods in anonymous namespaces.

In this case, I see why it could be useful to move these functions to the `polyscope.h` header, so when building a fancy custom GUI like yours, you can call them manually. I just pushed a small commit to your branch which makes that change.

 > ImGUI parameters getting overwritten
 
I think the problematic code is around here: https://github.com/xarthurx/polyscope/blob/master/src/polyscope.cpp#L137-L147 . `pushContext()` gets called on every `show()` (and some other times too), and it's making some ImGui style calls that are not currently respecting the callback added in this branch.

I agree that it makes sense to (a) clean up & simplify the places where Polyscope configures ImGui, and (b) give the user a way to adjust that configuration. Because Polyscope needs to be able to re-do this configuration whenever a context gets pushed, it is indeed probably to do this by allowing the user to specify some callbacks.

I think the TODO here is to refactor the current Polyscope ImGui style code to consist of just two calls, one named something like `prepareFonts()` which gets called exactly once and sets the font pointers, and another like `setImGuiStyle()`  which gets called many times and sets style parameters. These functions will internally _either_ apply the default font/style, _or_ call a user-provided callback doing the same thing, if one exists. Does that sounds reasonable?

**Comment by xarthurx** [comment]
> I think the TODO here is to refactor the current Polyscope ImGui style code to consist of just two calls, one named something like `prepareFonts()` which gets called exactly once and sets the font pointers, and another like `setImGuiStyle()` which gets called many times and sets style parameters. These functions will internally _either_ apply the default font/style, _or_ call a user-provided callback doing the same thing, if one exists. Does that sounds reasonable?

Yes, for what I have done with the ImGui, this should be enough.

**Comment by nmwsharp** [comment]
The changes mentioned above are now merged in #145! They'll be documented as soon as I rebuild the public docs page. I added you as a co-author on that new PR since it supersedes this one.

Feel free to reopen this or an issue if those changes still don't work for you. Thanks!

**Comment by xarthurx** [comment]
Great! Thank you for the work.
I'll give it try and let you know if I find sth new.

**Comment by xarthurx** [comment]
Hi @nmwsharp , I'd like to continue the discussion of the font here.

I'm looking at your `prepareImGuiFonts()` function, posted here directly for reference:
```

  ImGuiIO& io = ImGui::GetIO();

  // outputs
  ImFontAtlas* globalFontAtlas;
  ImFont* regularFont;
  ImFont* monoFont;

  { // add regular font
    ImFontConfig config;
    regularFont = io.Fonts->AddFontFromMemoryCompressedTTF(render::getLatoRegularCompressedData(),
                                                           render::getLatoRegularCompressedSize(), 18.0f, &config);
  }

  { // add mono font
    ImFontConfig config;
    monoFont = io.Fonts->AddFontFromMemoryCompressedTTF(render::getCousineRegularCompressedData(),
                                                        render::getCousineRegularCompressedSize(), 16.0f, &config);
  }

  // io.Fonts->AddFontFromFileTTF("test-font-name.ttf", 16);

  io.Fonts->Build();
  globalFontAtlas = io.Fonts;

  return std::tuple<ImFontAtlas*, ImFont*, ImFont*>{globalFontAtlas, regularFont, monoFont};
```

Do you have any purpose to use the `regularFont` and `monoFont`?
I searched the whole library and didn't find any use of the two fonts. 

From my point of view, if you check the [ImGui Font Guide](https://github.com/ocornut/imgui/blob/master/docs/FONTS.md), an easy way for the user is to define their own fonts, and use `pushFont` function for in-place use when defining the GUI.

So what I would recommend for this lib, from a user's perspective, is to hide the settings of the default fonts, making it defaults, and provide an optional callback function after the default settings for the user without any return values. 

In this way, the user can just do something like:
```
fontCallback(){
  auto& io = ImGui::GetIO();
  io.Fonts->Clear();

  // first one is the default
  fontLgt = io.Fonts->AddFontFromFileTTF(
    (data_path + "font/Roboto-Light.ttf").c_str(), 12 * hidpi_scaling_);
  fontReg = io.Fonts->AddFontFromFileTTF(
    (data_path + "font/Roboto-Regular.ttf").c_str(), 12 * hidpi_scaling_);
  fontMed = io.Fonts->AddFontFromFileTTF(
    (data_path + "font/Roboto-Medium.ttf").c_str(), 15 * hidpi_scaling_);
}
```
to add their own fonts, and use it when setting up the GUI using `pushFont` and `PopFont`.

This reduces the complexity of asking the user to provide three font pointers, which many users don't understand the difference, as well as the need to do `io.Fonts->Build()`.

**Comment by nmwsharp** [comment]
> Do you have any purpose to use the `regularFont` and `monoFont`?

They are not used right now, but the idea is that Polyscope will internally activate the regular font to render most UI items, and `monoFont` to render numerical values, like what you see in the table pane when you click on a point/vertex/etc. I ran out of time to drop in all of those activate font commands, but I would like to keep these around with the plan of doing that in the future.

 > So what I would recommend for this lib...

I'm not sure I fully understand. Are you saying that it's not possible to customize the fonts in the way you want with the current setup, or just that the current strategy is unintuitive?

I suppose we do need to distinguish two distinct sub-cases of customizing fonts: (a) changing the fonts which Polyscope uses internally to render its own UIs, and (b) adding additional fonts for use by the user's UIs. I had been thinking you mainly wanted to do (a), but perhaps you're thinking more about (b).

That being said, I still think the current set up is pretty decent. It's entirely possible to do either (a) or (b), unless I'm missing something. I also think it's no big deal if this requires some additional ImGui calls, because this is something that only a small number of advanced users will ever do, and we can assume they are familiar with ImGui.

One thing I do definitely agree on with is that we can make it simpler for users who merely want to do (b) 🙂  I've added a note to the docs [here](http://polyscope.run/features/callbacks_and_UIs/#imgui-fonts-callback) explaining how to replicate the existing font loading in the case where you simply want to add extra fonts. Does that sounds reasonable?

**Comment by xarthurx** [comment]
OK, now I see the intention. Yes, I disabled the default GUI and forgot about the default fonts.
I fully agreed with you that there should be default global fonts used by the lib, in this case, your three font pointers, and additional fonts that the user want for custom settings.

> One thing I do definitely agree on with is that we can make it simpler for users who merely want to do (b) 🙂 I've added a note to the docs here explaining how to replicate the existing font loading in the case where you simply want to add extra fonts. Does that sounds reasonable?

With this, I think both a) and b) should be resolved good enough!

**Pull request closed without merging**
