### PR TITLE
Draft: New Feature - Groups, i.e. creating collections of structures in the UI for quickly showing - hiding layers / hierarchies of structures  

### PR DESCRIPTION
**Pull request by danieldugas**
Hi, I'm a huge fan of Polyscope! I use it all the time for debugging / visualizing.

One feature I've been sorely needing is a way to group structures into hierarchies which can then be quickly enabled / disabled (as can be done in e.g. Unity, RHINO, etc). After reading the contribution guide, I went ahead and made a quick prototype implementation (and matching python bindings, tested with a really basic test script)

**This is a Draft of a PR**: before I put in more polishing work to ensure this fits the guidelines (unit tests, documentation update, etc..), I wanted to quickly check whether this is at all a feature others would find useful, and more importantly whether you agree that it belongs in polyscope.

Quick overview of what this does:

- Groups can have a single parent (another group), but several children (both groups and structures) - implemented in groups.cpp and groups.h
- Groups show up in the UI, in their own node under Structures
- Groups can be enabled / disabled by clicking on the checkbox, which enables / disables all their child structures and groups.
- For a quick functionality check, I've updated the python bindings (https://github.com/danieldugas/polyscope-py/tree/feature/structure_groups) and created a temporary build-and-test script.

Screenshot from 2023-02-20 11-37-04

If you do greenlight this, there's still a few things which need to be done (by me - although if any volunteers show up, help is always appreciated):
- Agreeing on the final API
- Documentation (both C++ and python)
- Unit tests
- Cleanup (test.py, run_build_and_test.sh)
- Also make and merge a PR on the polyscope-py repo
- Other required changes from your side

### CODE REVIEW

**Comment by nmwsharp** [comment]
This is great!! We certainly need better UI tools for managing large amounts of structures, and this is a very elegant solution that fits quite nicely into the setup.

Short answer is that I'm all-for it, and everything you described sounds good to me.

I particularly appreciate that it sounds like you're already considering "advanced" uses like nesting groups in groups, detecting cycles, displaying partially-enabled groups in the UI, etc. Let me know if there is anything more specific you would like feedback or help with.

I'm hoping to do a giant new version release in a couple weeks with many accumulated features (working on a big backend refactor in the `cuda_interop` branch, but that should be orthogonal to this feature). It would be great to include this in that release, though also no pressure if you don't have time to polish by then.

Also, this next release will be a major release with a few (small) breaking changes. So if any behavior needs to change in a backwards-incompatible way to enable your feature, that could be okay, feel free to mention it.

**Comment by danieldugas** [comment]
That's great! And thanks a lot for your quick reply!

Quick update:
- Unit tests (cpp) are added and working (also, found and fixed a few small kinks while writing tests)
- Unit tests (py) are also added and working on my end
- Added a documentation entry (py + cpp) under features/groups, with a demo video
- I'm opening corresponding PRs on polyscope-py (https://github.com/nmwsharp/polyscope-py/pull/26) and polyscope-docs (https://github.com/nmwsharp/polyscope-docs/pull/12)

What I can't do myself:
- someone to double check things are working on their end
- agree on the 'Groups' name (e.g. making sure it doesn't conflict with a potential future use case, ..., ?)
- someone to check that the documentation and API are reasonable / understandable

After that, if all is well I'll remove my test script and we should be able to merge (your call to make, obviously)

Regarding next version, behavior change: sounds good! As far as I can tell, no behavior change is needed.

**Comment by danieldugas** [comment]
@nmwsharp I merged master to allow the CI tests to pass, feel free to run the workflow again

**Comment by nmwsharp** [comment]
Awesome! Is this good-to-go on your end?

**Comment by danieldugas** [comment]
yes, it looks ready to merge here. The docs PR should be good as well (https://github.com/nmwsharp/polyscope-docs/pull/12).

After merging in this repository, the polyscope-py PR (https://github.com/nmwsharp/polyscope-py/pull/26) needs to be updated to point the git submodule to the new master commit, then it can be merged as well.

**Comment by nmwsharp** [comment]
Merged! Thank you for this! I pushed some commits above to make a few tweaks, but nothing major.

**Comment by nmwsharp** [comment]
Oh, I think there may be an issue here with deletion: if a structure gets deleted when it is in a group, then the group will hold a stale pointer, and probably segfault on the next draw cycle (right?). I merged anyway, because we can address that in a future commit, and it would not be the only part of Polyscope which is buggy when structures get deleted.

Anyway, can you think of any nice ways to handle that? One answer could be that each structure also has a list of groups which it is in, and in the destructor it removes itself from all groups. We could also probably handle it with smart pointers. I suppose the global list of structures in `polyscope.h` should really be `unique_ptr`s ...

**Comment by danieldugas** [comment]
Extra note: Looking back I remember my thought was that since sMap contains pointers to structures, groups would be equally (un)safe as sMap as long as we mirrored every sMap.erase with an equivalent removal from groups.

**Pull request merged**
